[build]
# builder နေရာကို ဖျက်ပြီး ဒါပဲချန်ထားပါမယ်

[build.nixpack]
# nixpack အတွက် လိုအပ်တဲ့ ဆော့ဖ်ဝဲလ်တွေကို ဒီလိုပြောင်းထည့်ပါမယ်
pkgs = ["ffmpeg", "deno"]

[deploy]
startCommand = "python3 -m HasiiMusic"
restartPolicy = "on-failure"
